server:
  port: 8080

#logging:
#  config: >-
#    file:./config/log4j2.yml

vaadin:
  frontend:
    hotdeploy: true
  allowed-packages: com.vaadin,org.vaadin,com.example.application
  # Launch the default browser when starting the application in development mode
  launch-browser: false

spring:
  ai:
    openai:
      api-key: not-used
      base-url: http://localhost:1234
      chat:
        options:
          model: qwen/qwen3-4b-2507
#          temperature: 1
          
