server:
  port: 8080

#в dev-config можно переопределить для своих настроек логера
#logging:
#  config: >-
#    file:./config/log4j2.yml

vaadin:
  frontend:
    hotdeploy: true
  allowed-packages: com.vaadin,org.vaadin,com.example.application
  # Launch the default browser when starting the application in development mode
  launch-browser: false

spring:
  ai:
    openai:
      api-key: not-used
      base-url: http://localhost:1234
      chat:
        options:
#          model: qwen/qwen3-4b-2507
          model: qwen/qwen3-vl-4b
#          temperature: 1

#  Не работают, смотри настройки в методе LmStudioConfig::chatModel
#  http:
#    client:
#      connect-timeout: 30s
#      read-timeout: 120s

#Директория куда будут загружаться временные файлы
upload:
  dir: >-
     D:\temp\uploads 

